name: GH-200 CoHack

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GH-200 Session from Himanshu!!!"

      - name: copy code into runner
        uses: actions/checkout@v6

      - name: List files
        run: ls -la

      - name: Generate ASCII Art
        run: |
          sudo apt-get install -y figlet
          figlet "GH-200 CoHACK"
          echo "-------------------------"
          figlet -f digital "GitHub Actions"
          echo "ASCII art generated"

      - name: Run Shell Script
        run: |
          chmod +x ./scripts/welcome.sh
          ./scripts/welcome.sh
